version: '2'

services:
  jekyll:
    image: jekyll/jekyll:latest
    command: jekyll serve --watch --force_polling --verbose -H 0.0.0.0
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll